name: build-and-deploy

on:
  push:
    paths:
    - '.github/workflows/build-and-deploy.yml'
    - 'src/**'
  pull_request:
    paths:
    - '.github/workflows/build-and-deploy.yml'
    - 'src/**'

env:
  has_v_tag: ${{ startsWith(github.ref, 'refs/tags/v') }}
  is_default_branch: ${{ github.ref == 'refs/heads/main' }}

jobs:

  build:

    runs-on: ubuntu-latest
    outputs:
      magic_value: '${{ env.has_v_tag }}'    
    steps:
    - name: 'Run Always'
      run: 'echo "always has_v_tag=$has_v_tag is_default_branch=$is_default_branch"'
    - name: 'If tagged'
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      run: 'echo "v-tagged"'
    - name: 'If tagged or default branch'
      if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
      run: 'echo "v-tagged or main"'
    - name: 'If default branch [env]'
      if: ${{ fromJSON(env.is_default_branch) }}
      run: 'echo "on default branch"'
    - name: 'If tagged [env]'
      if: ${{ fromJSON(env.has_v_tag) }}
      run: 'echo "tagged"'
    - name: 'If tagged or default branch [env]'
      if: ${{ fromJSON(env.has_v_tag) || fromJSON(env.is_default_branch) }}
      run: 'echo "v-tagged or main"'
      
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ fromJSON(needs.build.outputs.magic_value) }}
    steps:
    - name: 'Dump vars'
      run: 'echo "always has_v_tag=$has_v_tag is_default_branch=$is_default_branch"'
