name: Pseudo-CD
on:
  workflow_run:
    workflows: [Pseudo-CI]
    types:
      - completed
  workflow_dispatch:
    inputs:
      ci-run-id:
        type: number
        required: true
        description: "The ID of the build/CI workflow to use as source for artifacts."

jobs:
  cd:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - id: run-id
        name: 'Manual or Triggered?'
        run: |
          if ('${{ github.event_name }}' -eq 'workflow_run') {
            echo "artifacts-run-id=${{ github.event.workflow_run.id }}" >> $env:GITHUB_OUTPUT
          } elseif ('${{ github.event_name }}' -eq 'workflow_dispatch') {
            echo "artifacts-run-id=${{ inputs.ci-run-id }}" >> $env:GITHUB_OUTPUT
          } else {
            exit 1
          }
        shell: pwsh
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.2.1
        with:
          name: app
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.run-id.outputs.artifacts-run-id }}
      - name: Emulates a deploy
        run: |
          ls -l app*
          chmod +x app.sh
          ./app.sh
