name: Pseudo-CI
on:
  push:
    paths:
    - 'trigger/pseudo-ci'
  pull_request:
    paths:
    - 'trigger/pseudo-ci'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Emulates a build
        run: |
          echo "echo Hi" > app.sh
          chmod +x app.sh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: "app"
          path: "app.sh"
          if-no-files-found: error
          overwrite: true
